# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 043a672f04749c61f283c606554ee132ba7b12186fc7a0e86a98d275dc734dc5d5afaf2d35e66e0e2de988fc9f539562492653f467f54e9b2debeed1d3bb4491

test:
  secret_key_base: d5d7b313c1e9d341f4a035992d1139d76ede24fc5b8d8cd7c3c4c4dc564db869a4df8db27f7f3410d814fed7ad0c8ca88a1a8ba61e0cd104b75a3c944dff6cc0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
